### ISSUE TITLE
Anvil Parser version limitation makes it impossible to convert worlds from new versions like 1.20.1

### ISSUE THREAD

**Issue by Elevatorisbest** [potato1234x/minecraft-to-vmf#1]
I tried to use this script together with Anvil requirement (https://github.com/matcool/anvil-parser), and it kept throwing an error like this:

```
World Directory: C:\Users\rest of the directory
chunk to export x coord: 44
chunk to export z coord: 33
Error loading chunk at (44, 33) in C:\Users\rest of the directiories\region\r.1.1.mca: 'Tag DataVersion does not exist'
```

or alternatively

```
World Directory: C:\Users\rest of the directory
chunk to export x coord: 10
chunk to export z coord: 11
Error loading chunk at (10, 11) in C:\Users\rest of the directories\region\r.0.0.mca: 'Tag Level does not exist'
```

It was happening when I tried to use this script on worlds opened in version 1.20.1, but when I tried it on an archival save of my old SMP from something like 1.14, it worked correctly.

**Comment by potato1234x** [comment]
the script should be used with anvil-new not anvil-parser, thats my bad, i forgot to mention the dependencies in the readme 😅 
works with anvil-new!
